CREATE TABLE Brands (
  Id INT IDENTITY PRIMARY KEY,
  BrandName VARCHAR(255) NOT NULL
);

CREATE TABLE Cars (
  Id INT IDENTITY PRIMARY KEY,
  BrandId INT NOT NULL,
  ColorId INT NOT NULL,
  CarName VARCHAR(255) NOT NULL,
  ModelYear INT NOT NULL,
  DailyPrice DECIMAL(18,2) NOT NULL,
  Description VARCHAR(500) NULL
);

CREATE TABLE CarImages (
  Id INT IDENTITY PRIMARY KEY,
  CarId INT NOT NULL,
  ImagePath VARCHAR(255) NOT NULL,
  DateUploaded DATETIME2 NOT NULL
);

CREATE TABLE Colors (
  Id INT IDENTITY PRIMARY KEY,
  ColorName VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Customers (
  Id INT IDENTITY PRIMARY KEY,
  UserId INT NOT NULL,
  CompanyName VARCHAR(255) NULL
);

CREATE TABLE Rentals (
  Id INT IDENTITY PRIMARY KEY,
  CarId INT NOT NULL,
  CustomerId INT NOT NULL,
  RentDate DATETIME2 NOT NULL,
  ReturnDate DATETIME2 NULL,
);

CREATE TABLE OperationClaims (
  Id INT IDENTITY PRIMARY KEY,
  Name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Users (
  Id INT IDENTITY PRIMARY KEY,
  FirstName VARCHAR(255) NOT NULL,
  LastName VARCHAR(255) NOT NULL,
  eMail VARCHAR(255) NOT NULL UNIQUE,
  PasswordHash VARBINARY(MAX) NOT NULL,
  PasswordSalt VARBINARY(MAX) NOT NULL,
  Status BIT NOT NULL DEFAULT 1
);

CREATE TABLE UserOperationClaims (
  Id INT IDENTITY PRIMARY KEY,
  UserId INT NOT NULL,
  OperationClaimId INT NOT NULL,
);
